### ISSUE TITLE
Lab Report 1 Feedback 

### ISSUE THREAD

**Issue by mrkylesmith** [vs2961/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- You should include instructions for Windows users, and link for OpenSSH
- [x] All relevant code examples written with backticks (```)
- Good formatting and screenshot for your command examples!  Looks good. 
- [x] All screenshots correspond to the described steps
- Good use of screenshots to confirm that your commands were successful (eg. ls command on server to verify scp). 
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
- Format the commands with backticks in this section, that way they stand out to the reader. 
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Great job! 

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by vs2961** [comment]
I added the instructions for windows users and changed the screenshot for the command examples, but I'm unsure what I need to fix for the other two. Can you elaborate on them? Thanks

**Comment by mrkylesmith** [comment]
Thanks adding those things, looks like you covered everything.  Your Lab Report 1 looks great!  The other comments I added were just positive feedback I was giving you, but you completed all 7 tasks.  Well done!
